# Generated by Django 5.1.6 on 2025-03-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='content',
            field=models.TextField(default='Default About Us content'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(max_length=500, null=True, upload_to='posts/images'),
        ),
    ]
